### ISSUE TITLE
Getting trigger from uhfli demod raises ValueError on trying empty string enum member name

### ISSUE THREAD

**Issue by haroldmeerwaldt** [zhinst/zhinst-toolkit#148] opened 2022-05-19 12:15 UTC
Description
-----------
Hi there,

If you want to get the value of the trigger mode for a demodulator on the UHFLI, a ValueError is raised on an invalid enum member name :

```python
  File "C:\Users\XXX\AppData\Local\Temp\ipykernel_12200\1024915319.py", line 1, in <cell line: 1>
    uhfli.demods.demods0.trigger()

  File "D:\users\XXX\venv-3.9\lib\site-packages\zhinst\qcodes\qcodes_adaptions.py", line 208, in __call__
    return self.get(**kwargs)

  File "D:\users\XXX\venv-3.9\lib\site-packages\qcodes\instrument\parameter.py", line 650, in get_wrapper
    raise e

  File "D:\users\XXX\venv-3.9\lib\site-packages\qcodes\instrument\parameter.py", line 637, in get_wrapper
    raw_value = get_function(*args, **kwargs)

  File "D:\users\XXX\venv-3.9\lib\site-packages\zhinst\toolkit\nodetree\node.py", line 505, in _get
    value = self._parse_get_value(value, enum=enum, parse=parse)

  File "D:\users\XXX\venv-3.9\lib\site-packages\zhinst\toolkit\nodetree\node.py", line 459, in _parse_get_value
    getattr(self.node_info.enum, enum_info.enum)

  File "D:\users\XXX\venv-3.9\lib\site-packages\zhinst\toolkit\nodetree\node.py", line 239, in enum
    IntEnum(self.path, options_reversed, module=__name__)

  File "C:\python\Python39\lib\enum.py", line 386, in __call__
    return cls._create_(

  File "C:\python\Python39\lib\enum.py", line 510, in _create_
    enum_class = metacls.__new__(metacls, class_name, bases, classdict)

  File "C:\python\Python39\lib\enum.py", line 207, in __new__
    raise ValueError('Invalid enum member name: {0}'.format(

ValueError: ('Invalid enum member name: ', 'getting uhfli_demods0_trigger')
```

How to reproduce
----------------
```python
from zhinst.qcodes.driver.devices import UHFLI
from zhinst.toolkit.driver.devices import UHFLI as tkUHFLI
from zhinst.toolkit import Session

session = Session("192.168.x.xxx", 8004)
tk_uhfli = tkUHFLI("DEVXXXX", "UHFLI", session)
uhfli = UHFLI(tk_uhfli, session, "uhfli")

uhfli.demods.demods0.trigger()
```

If you dive into the code a bit, you can see that in zhinst.toolkit.nodetree.node.NodeInfo.enum, in line 235, the variable options_reversed gives (at least in my case):
```python
{'continuous': 0, '': 128, 'trigin2_falling': 2, 'trigin2_both': 3, 'trigin2or3_rising': 5, 'trigin3_falling': 8, 'trigin2or3_falling': 10, 'trigin3_both': 12, 'trigin2or3_both': 15, 'trigin2_low': 16, 'trigin3_low': 64, 'trigin2or3_low': 80, 'trigin2or3_high': 160, 'trigin0_rising': 1048576, 'trigin1_rising': 2097152, 'trigin2_rising': 4194304, 'trigin3_rising': 8388608, 'trigin0_high': 16777216, 'trigin1_high': 33554432, 'trigin2_high': 67108864, 'trigin3_high': 134217728}
```
The description of 128 is an empty string and IntEnum won't accept that.

Environment info
----------------

- Python version: 3.9.7
- zhinst-toolkit version: 0.3.3
- LabOne version: 22.02.29711
- zhinst version: 22.2.29711

Device/system information (if applicable)
-----------------------------------------

Additional information
----------------------

**Comment by tobiasah** [comment] 2022-05-19 13:41
@haroldmeerwaldt thanks for raising this issue. 

It's the first time I have seen that so thanks for spotting this. The problem originates from LabOne itself which apperantly defines the same keyword for multiple values. We will fix that for the next LabOne release. 
In the mean time you can use the kwarg `enum=False` for getting the value and use a number to set the value. 

`uhfli.demods[0].trigger(enum=False)`

**Comment by tobiasah** [comment] 2022-05-19 13:51
Just some side notes on your example code: 
1. One can instantiate a QCodes instance without creating a toolkit one. 

Either through a session:
```
from zhinst.qcodes import ZISession
session = ZISession("localhost")
uhfli = session.connect_device("devxxxx")
```
or directly
```
from zhinst.qcodes import UHFLI
uhfli = UHFLI("devxxxx", "localhost")
```
both of them will reuse existing sessions if they already exist. (Using an existing toolkit object is not necessary and comes with a lot of downsides (like additional unnecessary initialization)

2. We strongly discourage importing classes or modules within toolkit or qcodes. Everything one needs is exposed in the package directly (`from zhinst.qcodes import ...`). This also includes the devices which only should be created from the session through `connect_device`. Otherwise some of fundamental functionalities might not work as expected. 

3. Although QCoDeS also allows accessing list elements by attribute (`demods.demods0`) it is much more common to access it by item (`demos[0]`)

**Comment by tobiasah** [comment] 2022-05-19 13:52
I will leave this issue open until we have fixed the root cause so that others who stumble upon this problem find a quick solution. 

The next LabOne Release is planed end of August 2022 and will fix this issue.

**Comment by haroldmeerwaldt** [comment] 2022-05-23 11:05
Thank you for the explanation!

I had a delegate-like QCoDeS parameter. Passing enum=False to it worked, something like this:
```python
from functools import partial

submodule.add_parameter(
...
get_cmd=partial(parameter.get, enum=False),
...
)

```

**Comment by tobiasah** [comment] 2022-09-01 09:04
Yesterday we have release LabOne 22.08 together with this release this issue was solved as well. 

I will therefor close this issue. If any questions or problems persist feel free to reopen this issue at any time.

**Closed by tobiasah** 2022-09-01 09:04 UTC
Labels: bug
